# Generated by Django 2.0.3 on 2018-03-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
