# Generated by Django 2.0.3 on 2018-03-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltsapp', '0002_articles_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_text',
            field=models.TextField(),
        ),
    ]
