# Generated by Django 2.0.3 on 2018-03-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakp1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltsspeakingp1topic',
            name='sp1topic',
            field=models.CharField(max_length=1000),
        ),
    ]
