# Generated by Django 2.0.3 on 2018-03-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakp1app', '0003_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
